DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER (
  CUSTOMER_ID INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  );

INSERT INTO CUSTOMER (CUSTOMER_ID, NAME) VALUES
  (100, 'Dangote'),
  (101, 'Gates' ),
  (102, 'Alakija' );
  
  CREATE TABLE CUSTOMER (
  MAPPING_CUSTOMER_ID INT,
  MAPPING_ACCOUNT_ID INT,
   );
   
   INSERT INTO CUSTOMER (CUSTOMER_ID, NAME) VALUES
  (100, 200 ),
  (101, 201 ),
  (102, 202 );
  